CREATE TABLE Table_User (
    UserID INT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(50) NOT NULL,
    CreateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LoginDate TIMESTAMP
);

CREATE TABLE Table_Blog (
    ID INT PRIMARY KEY,
    Heading VARCHAR(255) NOT NULL,
    Brief TEXT,
    Content TEXT NOT NULL,
    PostDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(50) NOT NULL,
    UserID INT,
    FOREIGN KEY (UserID) REFERENCES Table_User(UserID)
);
